Fixing visiting a user profile via search
ssc-sp/datahub-portal pull request #1008
Opened 2024-02-06 17:04 UTC by Sean-Stilwell

Updates the search box in the topbar to use `/account?u=` instead of `/profile?u=`, avoiding a 404 error.

2024-02-07 14:38 UTC, ErikApption approved these changes

2024-02-07 20:45 UTC, yjmrobert requested changes

2024-02-07 20:45 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Layout/Topbar/SearchResultTab.razor
>          _ => "#"
Can you update these to use the `PageRoute` prefixes and whatnot?

2024-02-08 14:19 UTC, yjmrobert approved these changes

2024-02-08 14:19 UTC, merged