Workspace settings page updates
ssc-sp/datahub-portal pull request #1045
Opened 2024-03-04 19:43 UTC by shudsky

Added functionality to WorkspaceSettingsPage:
- Workspace leads can update workspace budgets and delete workspaces
- Admins can see the settings but not make any changes (fields are disabled)
- Other user types cannot see these settings

Updated DatahubAuthView so workspace leads are also required to have a project acronym specified.

Added basic .feature file for testing of WorkspaceSettingsPage.

2024-03-05 04:41 UTC, yjmrobert requested changes
Nice work, I like the update in progress UX! Do you happen to have a screenshot of it?


Let's update the disabled to work off the user roles via the NotAuthorized render component.

All that's left is to send the new Workspace Definition onto the queue. You might be able to reuse a method in one of the project management services. 

I'm more than happy to jump on a call to explain some of the topology as there are a lot of moving parts

2024-03-05 04:41 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Pages/Workspace/Settings/WorkspaceSettingsPage.razor
> +            }
That's the right idea, but I'll show you the `NotAuthorized` section in the Auth view that'll simplify things

2024-03-11 19:52 UTC, shudsky commented
Updated WorkspaceSettingsPage:
- Disabled works off Authorized / NotAuthorized components
- Added _requestManagementService await for sending to the queue

Also, here is what the UX looks like:
When budget has been changed:
![Screenshot 2024-03-11 153819](https://github.com/ssc-sp/datahub-portal/assets/67435074/e181d815-6051-4f8c-ad70-6595ca5dcaa1)

When saving the new budget:
![Screenshot 2024-03-11 153804](https://github.com/ssc-sp/datahub-portal/assets/67435074/30f18f2f-12a7-45f5-831d-3343ffd272c7)

2024-03-13 02:41 UTC, yjmrobert commented
Looks good! Great work on the UI/UX. I did a minor update to only allow datahub admins instead of workspace leads (just until we figure out how costing is going to work in production).

Cheers!

2024-03-13 02:42 UTC, merged