Prefix support in develop repo
ssc-sp/datahub-portal pull request #1075
Opened 2024-03-29 20:33 UTC by Nagendracv

Added new configuration element - resource_prefix_alphanumeric for storage name

## Description
resource_prefix_alphanumeric will be used only to construct storage name. The value expected in this variable is ideally expected to be small case, alphanumeric only... i.e. no special char like _ it -
Seperate pull request will be made for resourcemodules 

## How Has This Been Tested?
Using test run

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Unit test (new or update to tests)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (change that would cause documentation to be updated)
- [x] Configuration change (change that would affect the configuration of the application)

## Checklist:
- [x] PR is submitted to the correct branch `develop`.
- [x] Code follows the code style of this project.
- [x] Changes are covered by Specflow tests and all new or existing tests are passing.
- [ ] Any new or updated translatable strings have been added to the localization files.
- [ ] Necessary and relevant documentation has been created or updated.
- [ ] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

2024-04-02 17:25 UTC, yjmrobert requested changes
A few changes required as we discussed in our call. 

Please include a link to the infrastructure PR for the configuration updates as well!

2024-04-02 17:25 UTC, yjmrobert commented on ResourceProvisioner/src/ResourceProvisioner.Infrastructure/Services/TerraformService.cs
> +            .ToLower();
What do you think about moving this logic into the terraform code and replacing it here with a guard check instead?

2024-04-02 17:25 UTC, yjmrobert commented on ResourceProvisioner/src/ResourceProvisioner.Application/Config/ResourceProvisionerConfiguration.cs
> +    public string resource_suffix { get; set; }
I'm not sure about `resource_suffix` as it's only used for the terraform backend storage account and no other resources. 

Maybe just something simple like `tf_state_storage_suffix`

2024-04-02 17:25 UTC, yjmrobert commented on ResourceProvisioner/src/ResourceProvisioner.Infrastructure/Services/TerraformService.cs
> +        if (string.IsNullOrEmpty(suffix)) suffix = "ent" == env ? "tfbackend" : "terraformbackend";
I think there's more flexibility in the configuration if we were to set the default value to `terraformbackend` on the configuration object and then in the terraform code we can override it by having it set to `tfbackend`

Then we could clear up the logic here into a single line of string interpolation off the configuration object (similar to the other switch cases)

2024-04-02 17:25 UTC, yjmrobert commented on ResourceProvisioner/src/ResourceProvisioner.Infrastructure/Services/TerraformService.cs
> +    }
This isn't what we discussed. Was this added to the PR accidentally?

2024-04-05 18:38 UTC, Nagendracv commented on ResourceProvisioner/src/ResourceProvisioner.Infrastructure/Services/TerraformService.cs
> +        if (string.IsNullOrEmpty(suffix)) suffix = "ent" == env ? "tfbackend" : "terraformbackend";
Right, making the update

2024-04-05 18:38 UTC, Nagendracv commented on ResourceProvisioner/src/ResourceProvisioner.Infrastructure/Services/TerraformService.cs
> +    }
Yes by mistake. removing

2024-04-05 19:15 UTC, Nagendracv commented on ResourceProvisioner/src/ResourceProvisioner.Infrastructure/Services/TerraformService.cs
> +            .ToLower();
Making the update

2024-04-05 19:23 UTC, Nagendracv commented on ResourceProvisioner/src/ResourceProvisioner.Application/Config/ResourceProvisionerConfiguration.cs
> +    public string resource_suffix { get; set; }
suffix is the part which will be set to terraformbackend in the configuration, and in the prod version it will be tf or tfbackend

2024-04-08 13:37 UTC, yjmrobert commented on ResourceProvisioner/src/ResourceProvisioner.Application/Config/ResourceProvisionerConfiguration.cs
> +    public string resource_suffix { get; set; }
Gotcha, let's specify that it's only for the terraform backend and not a suffix for all resources

2024-04-11 20:49 UTC, Nagendracv commented on ResourceProvisioner/src/ResourceProvisioner.Application/Config/ResourceProvisionerConfiguration.cs
> +    public string resource_suffix { get; set; }
updated to storage_suffix

2024-04-12 16:04 UTC, yjmrobert approved these changes

2024-04-12 17:57 UTC, merged