2216 sending error data on error caught by ErrorBoundary
ssc-sp/datahub-portal pull request #1104
Opened 2024-04-24 13:16 UTC by vb-ssc

Added code to automatically submit error message and stack trace as a bug report.

## Description
Currently, if a user encounters the error screen, it's up to them to report it.

The error message and stack trace should be automatically tracked in ADO.

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Unit test (new or update to tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [ ] Configuration change (change that would affect the configuration of the application)

## Checklist:

- [ ] PR is submitted to the correct branch `develop`.
- [ ] Code follows the code style of this project.
- [ ] Changes are covered by Specflow tests and all new or existing tests are passing.
- [ ] Any new or updated translatable strings have been added to the localization files.
- [ ] Necessary and relevant documentation has been created or updated.
- [ ] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

2024-05-06 13:06 UTC, yjmrobert requested changes
I think I merged fixes for those failing unit tests in the CI pipeline into develop. Merging develop back might resolve that.

2024-05-06 13:06 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Pages/Account/Achievements/AchievementsPage.razor
> +        }
Wouldn't this always throw an exception the moment you have any users?

2024-05-06 13:06 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Pages/_Host.cshtml
> +}
Let's collocate the javascript with the component so we don't pollute the global namespace. See the second example here:

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?view=aspnetcore-8.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component


```csharp
module = await JS.InvokeAsync<IJSObjectReference>("import", 
    "./_content/AppJS/Components/Pages/JsCollocation3.razor.js");
```

A good reference would be the `FileExplorer.razor` and collocated files (`.razor.cs` and `.razor.js`)

2024-05-06 13:06 UTC, yjmrobert commented on Portal/test/Datahub.Tests/ErrorBoundaryTests.cs
I'm impressed you got this working! Will be very helpful to have as a reference for the next person 💯

2024-05-06 13:06 UTC, yjmrobert commented on Portal/src/Datahub.Application/Configuration/IDatahubPortalConfiguration.cs
I'm not convinced on the interface, any reason why not just bind it from the test config and inject the base object?

ie, 
```csharp
var configuration = new ConfigurationBuilder()
            .AddEnvironmentVariables()
            .AddJsonFile("appsettings.test.json", optional: true)
            .Build();

var datahubPortalConfiguration = new DatahubPortalConfiguration();
configuration.Bind(datahubPortalConfiguration);

...

ctx.Services.AddSingleton(datahubPortalConfiguration);
```

2024-05-06 13:56 UTC, vb-ssc commented on Portal/src/Datahub.Portal/Pages/_Host.cshtml
> +}
I added that to _Host  because it already have function `blazorGetTimezoneOffset()` . Will move my two functions to  JsCollocation

2024-05-09 18:06 UTC, vb-ssc commented on Portal/src/Datahub.Application/Configuration/IDatahubPortalConfiguration.cs
fixed

2024-05-14 20:28 UTC, yjmrobert approved these changes

2024-05-14 21:12 UTC, merged