House cleaning and proxy updates
ssc-sp/datahub-portal pull request #1272
Opened 2024-08-08 19:01 UTC by yjmrobert

## Description

General house cleaning, mostly fixed failing unit tests and some reverse proxy issues

## How Has This Been Tested?

Visually and unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Unit test (new or update to tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [x] Configuration change (change that would affect the configuration of the application)

## Checklist:

- [x] PR is submitted to the correct branch `develop`.
- [x] Code follows the code style of this project.
- [x] Changes are covered by Specflow tests and all new or existing tests are passing.
- [x] Any new or updated translatable strings have been added to the localization files.
- [x] Necessary and relevant documentation has been created or updated.
- [x] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

2024-08-08 21:15 UTC, ErikApption requested changes

2024-08-08 21:15 UTC, ErikApption commented on Portal/src/Datahub.Core/DatahubModuleContext.cs
why are you resuscitating this file? We shouldn't use the module stuff because I found out that the assembly scanning takes a lot of time on startup

2024-08-08 21:15 UTC, ErikApption commented on Portal/src/Datahub.Core/IDatahubModule.cs
zombie land

2024-08-08 21:15 UTC, ErikApption commented on Portal/src/Datahub.Infrastructure/ConfigureServices.cs
> -        if (DevTools.IsDevelopment())
this is rolling back some of the changes I did - I tried to centralize the tests for dev env instead of having them all over with string

2024-08-08 21:15 UTC, ErikApption commented on Portal/src/Datahub.Portal/Middleware/WorkspaceAppMiddleware.cs
this one really should go - it is a risk to keep it

2024-08-08 21:32 UTC, yjmrobert commented
Gah my merge 5174d5312218b4d864f15f24f41d4351da7bdb10 here didn't properly complete because of the githook scripts. Will fix it and push

@ErikApption

2024-08-09 14:11 UTC, ErikApption commented
ah this makes a lot more sense

2024-08-09 14:11 UTC, ErikApption approved these changes

2024-08-09 14:16 UTC, Sean-Stilwell approved these changes

2024-08-09 15:01 UTC, merged