✨ UI Changes - Removing usage of PersonalSidebar
ssc-sp/datahub-portal pull request #1284
Opened 2024-08-22 14:16 UTC by Sean-Stilwell

## Description

This PR makes a series of UI changes requested by Deb:

- The PersonalSidebar is no longer displayed.
    - Workspace and Learn sidebars are still displayed.
- A new Settings page is added that combines everything previously under /account/.
- Cards for Recent Links, Create a New Workspace, and to access the Explore page are added to the Home page.
- My Workspaces is now split into Admin/Lead, Collaborator, and Guest workspaces (if a user has any for each role).
- Minor changes to naming of pages.

![image](https://github.com/user-attachments/assets/0e61aec9-2480-4b1e-a4c1-20ee0ceae10e)

![image](https://github.com/user-attachments/assets/69def20a-c1da-40b9-8d70-b81515a2c2d5)

![image](https://github.com/user-attachments/assets/cfb1a18a-ff88-4f7b-b7c4-bb3f2a928cb2)

## How Has This Been Tested?

Locally tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Unit test (new or update to tests)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (change that would cause documentation to be updated)
- [ ] Configuration change (change that would affect the configuration of the application)

## Checklist:

- [x] PR is submitted to the correct branch `develop`.
- [x] Code follows the code style of this project.
- [ ] Changes are covered by Specflow tests and all new or existing tests are passing.
- [ ] Any new or updated translatable strings have been added to the localization files.
- [x] Necessary and relevant documentation has been created or updated.
- [x] There are either no changes to the application's configuration or the necessary changes in the infrastructure repository are included in a separate PR.

2024-08-22 15:41 UTC, Sean-Stilwell commented on Portal/src/Datahub.Portal/Layout/PortalLayout.razor
Wondering if anyone has a better idea for how to hide the sidebar everywhere except learn/workspaces. This works but not sure if anyone has something cleaner to suggest.

2024-08-22 19:41 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Layout/PortalLayout.razor
I wonder if it would make more sense to refactor the `MudDrawer` into a shared component and then we could move it down into the `SectionOutlet`'s own rendering logic

2024-08-22 19:43 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Layout/PortalLayout.razor
ie, the pages that want a drawer
```razor
<SectionContent SectionName="side-bar">
  <DHSideDrawer>
    <PersonalSidebar/>
  </DHSideDrawer>
</SectionContent>
```

and then we'd have `DHSideDrawer`
```razor
<MudDrawer
    Width="320px"
    Variant="DrawerVariant.Persistent"
    Open
    Overlay="false"
    Style="@_sideBorderStyle"
    Elevation="0"
    ClipMode="DrawerClipMode.Always" Breakpoint="Breakpoint.Always">
      <MudDrawerContainer>
          @ChildContent
      </MudDrawerContainer>
</MudDrawer>
```

2024-08-22 20:06 UTC, yjmrobert reviewed
Code looks good and lines up with the requested layout - nice work.

I'm still not convinced on the layouts for the landing and settings pages.  I think it merits some further discussions and measuring of where it improves or degrades the user experience before we wholly commit to the changes.

2024-08-23 14:02 UTC, yjmrobert requested changes
Looks like the pictures aren't working on the update
![image](https://github.com/user-attachments/assets/a318f591-0daf-4bc8-8fee-72bae91bd938)

vs 

![image](https://github.com/user-attachments/assets/da31ef8d-4e0a-40ae-86b2-fdc26d81f3d5)


Other than that I'm good to merge it.

2024-08-23 14:41 UTC, Sean-Stilwell commented
@yjmrobert Fixed with newest commit

![image](https://github.com/user-attachments/assets/f109c055-87c1-4e15-acbd-4703f8707a15)

2024-08-26 14:33 UTC, davidreneuw approved these changes

2024-08-26 14:33 UTC, davidreneuw approved these changes

2024-08-30 11:20 UTC, yjmrobert approved these changes

2024-08-30 11:21 UTC, merged