🐛 Swapping the announcement editor to use proper pageroute when saving
ssc-sp/datahub-portal pull request #1335
Opened 2024-09-17 18:04 UTC by Sean-Stilwell

# Pull Request

## Description

Currently, the announcement editor redirects admins to `/news` instead of `/announcements` when saving an announcement

It's not an urgent bug, the announcement still saves properly, just a bit annoying for admins

## Related Issues

## Changes

- Swaps both `/news` redirects to `Localizer["/announcements"]`

## Testing

Tested locally

## Checklist

- [x] Code follows dotnet coding standards
- [x] Documentation updated (if necessary)
- [x] Tests added/updated (if necessary)

2024-09-18 12:44 UTC, yjmrobert requested changes
I don't think it's a good idea to have the URL depend on our localization. Can we use the page routes and current culture instead?

2024-09-18 12:55 UTC, Sean-Stilwell commented
> I don't think it's a good idea to have the URL depend on our localization. Can we use the page routes and current culture instead?

I've swapped it to use PageRoutes (my bad). 

We've been using Localizer for our url path i18n everywhere else, if you have an alternative approach I can work on swapping it.

2024-09-18 13:02 UTC, yjmrobert commented
> We've been using Localizer for our url path i18n everywhere else, if you have an alternative approach I can work on swapping it.

A few ideas

- we can add a method like `CulturedPageRoute(string englishPageRoute)` to `CultureService` that would check the current culture and return if english, otherwise do a dictionary lookup if it's in french
- we could also add an extension method like `NavigateWithCultureTo(string englishUrl, CultureService cultureService)` to the NavigationManager which would reference the previous method

2024-09-19 18:32 UTC, yjmrobert approved these changes

2024-09-19 18:32 UTC, merged