🔧 Terms & Conditions on login
ssc-sp/datahub-portal pull request #1474
Opened 2024-11-26 19:36 UTC by davidreneuw

# Pull Request

## Description

Adds the terms and conditions checkbox on login page as well.

## Related Issues

## Changes

- T&C checkbox on login
- Fix some of the wording (removing the word "trial")
- Remove localization duplicates

## Testing

- Existing tests pass

## Checklist

- [x] Code follows dotnet coding standards
- [x] Tests added/updated to cover changes

2024-11-26 20:04 UTC, Sean-Stilwell submitted a review, later dismissed
Nice work!

![image](https://github.com/user-attachments/assets/dd8a826b-6620-4534-a13c-a8c961fc0cd3)

Small i18n issue with this message, not sure where it comes from though. I encountered it by putting in my email then clicking Login immediately.

Alternatively you could disable the Login button while the checkbox is unchecked

2024-11-26 21:32 UTC, ErikApption requested changes

2024-11-26 21:32 UTC, ErikApption commented on Portal/src/Datahub.Portal/i18n/localization.fr.json
> -  "Changes to workspace have been saved": "Les modifications apportées à l'espace de travail ont été enregistrées",
Are you sure these entries are not used?

2024-11-26 21:42 UTC, davidreneuw commented on Portal/src/Datahub.Portal/i18n/localization.fr.json
> -  "Changes to workspace have been saved": "Les modifications apportées à l'espace de travail ont été enregistrées",
Those were all marked as duplicates. For example, "Changes to workspace have been saved" is on line 451, "Queued Terraform update for workspace changes" is on line 2063, etc etc

2024-11-26 22:48 UTC, ErikApption submitted a review, later dismissed

2024-11-27 13:24 UTC, Sean-Stilwell commented
Just noticed this, could you swap "modalités et conditions" to "conditions générales"? We use that translation everywhere else so would be good to be consistent

2024-11-28 18:48 UTC, ErikApption approved these changes

2024-11-28 18:48 UTC, merged