Sg/accessibility skip link
ssc-sp/datahub-portal pull request #1518
Opened 2024-12-23 20:17 UTC by shudsky

# Pull Request

## Description
Adding UI to skip links ("skip to main content" and "skip to navigation"):
![image](https://github.com/user-attachments/assets/f92e5de9-0ea0-4069-a196-8acc024b6584)
![image](https://github.com/user-attachments/assets/bd3c5df2-eaf5-43e5-826d-129b17a9ae2f)

## Related Issues

## Changes
Adding UI to skip links for accessibility
- Colouring is the "Primary" colour for the DHButtons
- Covers part of the government logo

## Testing
Tested visually

## Checklist

- [X] Code follows dotnet coding standards
- [X] Tests added/updated to cover changes

2025-01-07 20:08 UTC, davidreneuw approved these changes, later dismissed

2025-01-09 14:11 UTC, Sean-Stilwell requested changes, later dismissed
I might be missing something, but I'm not sure what the buttons are intended to do. On my local testing, they just redirect to the `/home` page.

Also, is the UI intended to cover the topbar like that?

2025-01-09 16:11 UTC, shudsky commented
@Sean-Stilwell They redirect to the #maincontent and #nav sections of the page - if you look at how it works in production, it does the same thing but there's no UI telling you what's happening other than the link at the bottom (see here): 
![image](https://github.com/user-attachments/assets/1705945e-ba53-448c-afa0-be33da26e8fa)
Also, I think you might have been away when I asked about how the skip links should look and I believe the navigation bar at the top will be getting reworked anyway, so having the UI appear over the gov logo wasn't going to be a huge issue, especially since there's not really another clean option anyway as it has to appear before the Home/Announcements/Resources/Support buttons at the top.

2025-01-21 16:48 UTC, davidreneuw commented
Turned it into a component, forced the focus change with some javascript, fixed up the css and made a ScreenReaderNavigation component that is dynamic based on which IDs are present in the DOM

@ErikApption its ready to be reviewed/merged

2025-01-21 16:54 UTC, ErikApption approved these changes, later dismissed

2025-01-21 16:55 UTC, davidreneuw approved these changes, later dismissed

2025-01-21 18:56 UTC, davidreneuw approved these changes

2025-01-21 19:05 UTC, merged