Migrated UserTracking models into the Portal context
ssc-sp/datahub-portal pull request #747
Opened 2023-05-05 13:34 UTC by nicksalt

Closes #726

2023-05-05 14:22 UTC, iroelperez commented on Portal/src/Datahub.Core/Migrations/Core/DatahubProjectDBContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(450)");
This is a bit too large string field for a user ID, I think if you don't specify the length, they default to 450.

2023-05-05 14:23 UTC, iroelperez approved these changes

2023-05-05 17:11 UTC, yjmrobert requested changes
Nice work, a few changes related to what's coming down the pipeline in the next few iterations

- Could we have the FKs link off the `PortalUser` int id
- Since we're switching from NoSQL, we can probably drop `UserRecent` holding class and just have the two DbSets for recent links and settings

It's been awhile since I've dug around there so let me know if I'm off base w/ the requested changes

2023-05-05 17:12 UTC, yjmrobert commented
> 

It's been awhile since I've dug around there so let me know if I'm off base w/ the requested changes

2023-05-05 18:54 UTC, nicksalt commented on Portal/src/Datahub.Core/Migrations/Core/DatahubProjectDBContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(450)");
Resolved in d8c280b

2023-05-05 19:04 UTC, iroelperez approved these changes

2023-05-08 14:24 UTC, yjmrobert approved these changes

2023-05-08 15:53 UTC, merged