Tab for uploader code generation
ssc-sp/datahub-portal pull request #811
Opened 2023-06-06 21:39 UTC by ErikApption

- minor rework in file explorer to add a container level to the u/d options
- new uploader code generation in new tab
- configuration parameter to hide the new uploader tab

2023-06-08 14:10 UTC, yjmrobert requested changes
Looks good, just need to restructure the folders to match the other projects

```
Datahub/
├─ Portal/
│  ├─ src/
│  ├─ test/
├─ Uploader/
│  ├─ src/
│  │  ├─ Uploader.Shared/
│  │  ├─ Uploader.MAUI/
```
Something like the above

2023-06-08 14:10 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Controllers/PrivateStorageController.cs
> +    }
🌎

2023-06-08 14:10 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Controllers/PrivateStorageController.cs
> +    }
Just highlighting the tests are still here 😄

2023-06-08 14:10 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Controllers/PrivateStorageController.cs
> +    }
Is this a health check?

2023-06-08 14:29 UTC, ErikApption commented on Portal/src/Datahub.Portal/Controllers/PrivateStorageController.cs
> +    }
that's a merge error - not sure why there are there

2023-06-08 14:30 UTC, ErikApption commented on Portal/src/Datahub.Portal/Controllers/PrivateStorageController.cs
> +    }
another merge error

2023-06-08 15:14 UTC, yjmrobert commented
> Looks good, just need to restructure the folders to match the other projects
> 
> ```
> Datahub/
> ├─ Portal/
> │  ├─ src/
> │  ├─ test/
> ├─ Uploader/
> │  ├─ src/
> │  │  ├─ Uploader.Shared/
> │  │  ├─ Uploader.MAUI/
> ```
> 
> Something like the above

Suggestion to rename from `Uploader` to `Desktop` 👍

2023-06-13 03:13 UTC, ErikApption commented
@yjmrobert I renamed MAUI to Desktop

2023-06-14 12:53 UTC, merged