Assorted UI Changes
ssc-sp/datahub-portal pull request #925
Opened 2023-10-26 15:47 UTC by Sean-Stilwell

This makes several simple changes to the UI.

FSDH Login Page
- Centered the title, log in, and registration areas in their column.
- Changed the sizing of columns based on screen to prevent some weird formatting issues.
- Minor grammar changes

Welcome Message
- Previously uses UTC, making it say "Good Evening" at about noon in EST, for example.
- Changed to retrieve the user's local date and time with JSInterop and use that instead.

404 page
- Previously just a cute picture of a dog.
- Added content that directs people to fill out a Support Request Form and a button to return to home page.

ToC Page
- Adds a button to exit the page. Previously, you could only exit by backing out or entering a URL.

2023-10-30 14:55 UTC, ErikApption commented on Portal/src/Datahub.Portal/App.razor
can we resuscitate the dog

2023-10-30 14:56 UTC, yjmrobert requested changes

2023-10-30 14:56 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Pages/Landing/WelcomeBanner.razor
> +        _module = await _jsRuntime.InvokeAsync<IJSObjectReference>("import", "./Pages/Landing/WelcomeBanner.razor.js");
Need to dispose of this if we're going to reference it.

You can `@implements IAsyncDisposable` on the component and then dispose of it in `IAsyncDispoable.DisposeAsync`

see https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#javascript-isolation-in-javascript-modules

2023-10-30 19:40 UTC, ErikApption commented on Portal/src/Datahub.Portal/App.razor
@Sean-Stilwell  here is a tentative 404 cat https://www.flickr.com/photos/aloha75/8369751532/

2023-11-01 13:32 UTC, yjmrobert approved these changes

2023-11-01 13:32 UTC, merged