Workspace inactivity notifier
ssc-sp/datahub-portal pull request #926
Opened 2023-10-27 17:07 UTC by davidreneuw

Implemented the following:

- **Project inactivity scheduler function**: goes through all projects daily and schedules them to get their inactivity info updated using the inactivity updater function.
- **Project inactivity updater function**: for each queue element, will calculate days since the most recent login date of any user in the given workspace. Using the new project inactivity service, will interact with the` Project_Inactivity` db table to update the `DaysSinceLastLogin` of a project. Then it will send the queue item to the inactivity notifier function.
- **Project inactivity notifier function**: for each project, will check if a notification is required, and will notify all users of a workspace if it is required. A list of notification days are provided in `appsettings` (i.e. `23,28,30`). The function will send emails for all notification days once `DaysSinceLastLogin` reaches the notification day, except for the last "notification" day (in this case, 30), where instead of sending the email, it will start the deletion process (this is not implemented yet). If a workspace is `Whitelisted`, it will not be affected by this, though if a `RetirementDate` for a workspace is provided and that date is today, then the deletion process will also be started.
- **Project inactivity service**: allows interacting with the corresponding table. Implemented the necessary function so that we can later on set retirement dates and whitelisting for workspaces using a UI.

_**Notes**_: 

1. I haven't tested any of this yet and am mostly looking for conceptual/logical feedback
2. When implementing the new `Project_Inactivity` table in `DatahubProjectDBContext`, I did not understand how to properly set up the table in the `OnModelCreating` function. I will need help with that
3. This was mostly based on the existing work Iroel has done with project usage notifying

2023-10-30 13:38 UTC, ErikApption requested changes, later dismissed

2023-10-30 13:38 UTC, ErikApption commented on Portal/src/Datahub.Core/Model/Projects/Project_Inactivity.cs
@yjmrobert Do you think we should put whitelisted on the project object?

2023-11-28 17:51 UTC, davidreneuw commented
Note: THIS REQUIRES A CHANGE TO `local.appsettings.json` IN `Datahub.Functions` (new queue names) AS WELL AS `appsettings.json` IN `Datahub.Portal` (delete queue name)

2023-11-29 17:52 UTC, yjmrobert approved these changes

2023-11-29 17:52 UTC, yjmrobert commented on Portal/src/Datahub.Core/Model/Projects/Project_Inactivity.cs
We'd considered that, as well as just wrapping it in a project extension method that would get the inactivity bool if the `PortalUser`s were loaded.

That table is getting a huge mish-mash of random fields and I'd like to clean it up before production release. I'm good with either sticking it on the project object to clean up later though

2023-11-29 20:11 UTC, merged