Revamped the page alerts
ssc-sp/datahub-portal pull request #963
Opened 2023-12-15 20:40 UTC by davidreneuw

Revamped page alerts and created two new alerts: one that shows on any page and describes the process of navigating the platform and creating a workspace, one that shows on the workspace page and describes navigating a workspace, adding metadata, inviting users and requesting tools from the toolbox.

Made a few fixes to the learn page so that there are no errors when it first loads. Also changed its layout so that the content has more space.

Made a fix to the account customization page and UserInformationService so that it properly saves changes to user settings. Added page alert related settings.

2023-12-20 14:23 UTC, ErikApption commented on Portal/src/Datahub.Core/Components/PageBanner/DHPageAlert.razor.cs
This looks great - wondering if it would make more sense to put the page alerts in a json file

2023-12-20 14:31 UTC, ErikApption commented on Portal/src/Datahub.Core/Services/IUserSettingsService.cs
> +#nullable enable
we prob should look at enabling nullable globally there

2023-12-20 14:36 UTC, ErikApption approved these changes

2024-01-02 14:14 UTC, yjmrobert requested changes

2024-01-02 14:14 UTC, yjmrobert commented on Portal/src/Datahub.Core/Components/PageBanner/DHPageAlertDialog.razor
> +﻿<MudDialog Style="height: 830px" ContentStyle="height: 100%">
Should be okay here as we have no screen requirements, but it might make sense to have it set a min and max height based on the `vh` measurement

2024-01-02 14:14 UTC, yjmrobert commented on Portal/src/Datahub.Portal/Layout/LearnLayout.razor
I think there might be a simpler way to handle this. I'm wondering if we invert the dependency here and have the default layout be something like a `ContainerLayout.razor`, then we can simply wrap the body in a container.

Then if we update the default layout to the container layout we can just have the resources page implement the one without

2024-01-12 16:16 UTC, davidreneuw commented
@yjmrobert please have a look

2024-01-15 15:08 UTC, merged