BugReport queue function
ssc-sp/datahub-portal pull request #966
Opened 2023-12-19 20:51 UTC by davidreneuw

Created a BugReport Queue trigger function that creates ADO issues and emails Data Solutions email.
Created an EmailService that makes building emails easier for functions
Changed all functions to use the EmailService
Moved the email templates to a different folder
Created BugReportMessage and Sender so that Mediator can handle bug reports
Implemented BugReports in the HelpDialog and on System Error pages.
Unit tested the BugReport queue function and the EmailService.

2023-12-19 21:21 UTC, ErikApption commented on Portal/src/Datahub.Functions/EmailTemplates/bug_report.html
> +    Un rapport de bogue a été soumis et l'issue {id} a été créée sur <a href="{url}">Azure DevOps</a>. Description: {description}
Un rapport de bogue a ete soumis et le problème/ticket {id} a ete cree

2023-12-19 21:23 UTC, ErikApption commented on Portal/src/Datahub.Functions/Services/EmailService.cs
haven't done any other digging in code but didn't we already have an email service?

2023-12-19 21:24 UTC, ErikApption requested changes
Can you confirm that there is no duplication in emailservice in function and there is a minor suggestion for French translation in my comment

2023-12-19 21:34 UTC, davidreneuw commented on Portal/src/Datahub.Functions/Services/EmailService.cs
@ErikApption There is an email service in the Infrastructure project, the service I built could very well be merged into it. I just was not sure where to build the service (both interface and service inside Functions project v.s. interface in Application project and service in Infrastructure project, at which point I would have merged them)

2023-12-19 21:42 UTC, davidreneuw commented
> Can you confirm that there is no duplication in emailservice in function and there is a minor suggestion for French translation in my comment

I confirm there is no duplication between the EmailService I built and the two existing email services i.e. DatahubEmailService (in Infrastructure) and EmailNotificationService (in Core). Although they could probably be merged.

2023-12-20 14:19 UTC, ErikApption commented on Portal/src/Datahub.Functions/Services/EmailService.cs
makes sense, lets figure this one later once Yannick is back

2023-12-20 14:19 UTC, merged